import numpy as np
def reconstruct(U,s,V, flag_type): #rename/add/remove input variables as needed
    """ Reconstruct an approximate 2-d image matrix from the "compressed" variables
    generated by compress
    """
    assert(flag_type == True)
    S = np.diag(s)
    return U.dot(S).dot(V)