"""Homework 2, part 1
"""
from scipy import misc

def crop(F,T,B,L,R):
    """ Crop image represented by matrix F. T,B,L,R indicate 
    how much of the image should be removed from the top, bottom,
    left, and right of the original image.
    """

def smooth(F):
    """ Apply a simple smoothing procedure to image matrix F
    """
        
def compress(F2d,C):
    """ Construct a compression of 2-d image matrix F2d which
    requires C times the memory needed for F2d
    """

def reconstruct(a1,a2,a3): #rename/add/remove input variables as needed
    """ Reconstruct an approximate 2-d image matrix from the "compressed" variables
    generated by compress
    """


if __name__ == '__main__':
    #Read and display image
    F = misc.imread("image.jpg")
    plt.figure()
    plt.imshow(F)


# The code below can be used to test if
# the code is functioning in a "reasonable" manner.

#    T,B,L,R = 0.1,0.2,0.3,0.4
#    G = crop(F,T,B,L,R)
#    plt.figure()
#    plt.imshow(G)
    
#    G = smooth(F)
#    plt.figure()
#    plt.imshow(G)
    
#    a1,a2,a3 = compress(F.mean(2),0.1)
#    G = reconstruct(a1,a2,a3)
#    plt.figure()
#    plt.imshow(G,'gray')
